In [47]:
import pandas as pd
import numpy as np

In [48]:
ppr_2020 = pd.read_csv("./Fantasy Football Datasets/2020 PPR.csv")
std_2020 = pd.read_csv("./Fantasy Football Datasets/2020 Standard.csv")
adp_std_2021 = pd.read_csv("./Fantasy Football Datasets/2021 ADP Standard.csv")
adp_ppr_2021 = pd.read_csv("./Fantasy Football Datasets/2021 ADP PPR.csv")

In [49]:
ppr_2020.head()

,RK,ID,NAME,TEAM,POS,GAMES,PASSING YDS,PASSING TD,PASSING INT,RUSHING YDS,RUSHING TD,RECEIVING RECEPTIONS,RECEIVING YARDS,RECEIVING TDS,D - SACKS,D - INTERCEPTIONS,D - FF,D - FR,PTS/GAME,TOTAL POINTS
0,1,19801,Josh Allen,BUF,QB,16,4544,37,10,421,8,1,12,1,0.0,0,0,0,24.8,396.06
1,2,2593,Aaron Rodgers,GB,QB,16,4299,48,5,149,3,1,-6,0,0.0,0,0,0,24.0,383.26
2,3,20889,Kyler Murray,ARI,QB,16,3971,26,12,819,11,0,0,0,0.0,0,0,0,23.7,378.74
3,4,18878,Alvin Kamara,NO,RB,15,0,0,0,932,16,83,756,5,0.0,0,0,0,25.2,377.80
4,5,18890,Patrick Mahomes,KC,QB,15,4740,38,6,308,2,0,0,0,0.0,0,0,0,25.0,374.40

In [50]:
# get rid of defense columns
ppr_2020.drop(ppr_2020.columns[[14,15,16,17]], axis=1, inplace=True)
ppr_2020.head()

,RK,ID,NAME,TEAM,POS,GAMES,PASSING YDS,PASSING TD,PASSING INT,RUSHING YDS,RUSHING TD,RECEIVING RECEPTIONS,RECEIVING YARDS,RECEIVING TDS,PTS/GAME,TOTAL POINTS
0,1,19801,Josh Allen,BUF,QB,16,4544,37,10,421,8,1,12,1,24.8,396.06
1,2,2593,Aaron Rodgers,GB,QB,16,4299,48,5,149,3,1,-6,0,24.0,383.26
2,3,20889,Kyler Murray,ARI,QB,16,3971,26,12,819,11,0,0,0,23.7,378.74
3,4,18878,Alvin Kamara,NO,RB,15,0,0,0,932,16,83,756,5,25.2,377.80
4,5,18890,Patrick Mahomes,KC,QB,15,4740,38,6,308,2,0,0,0,25.0,374.40

In [53]:
ppr_2020['POS'].value_counts()
# from this we don't want: OLB, ILB, DST, SS, DE, FS, CB, LB, S, DT
# we do want: WR, RB, QB, K, TE
# will use dictionary to map these positions

WR     73
RB     46
QB     36
K      22
TE     21
OLB    20
ILB    20
DST    15
SS     12
DE     10
FS      9
CB      6
LB      5
S       3
DT      2
Name: POS, dtype: int64

In [54]:
# List containing desired posiitons
offense_list = ['WR', 'RB', 'QB', 'K', 'TE']

In [59]:
# filter to only have desired positions
ppr_2020 = ppr_2020[ppr_2020['POS'].isin(offense_list)]
ppr_2020['POS'].value_counts() # verify we only have offensive positions now.

WR    73
RB    46
QB    36
K     22
TE    21
Name: POS, dtype: int64

In [66]:
ppr_2020.head()

,RK,ID,NAME,TEAM,POS,GAMES,PASSING YDS,PASSING TD,PASSING INT,RUSHING YDS,RUSHING TD,RECEIVING RECEPTIONS,RECEIVING YARDS,RECEIVING TDS,PTS/GAME,TOTAL POINTS
0,1,19801,Josh Allen,BUF,QB,16,4544,37,10,421,8,1,12,1,24.8,396.06
1,2,2593,Aaron Rodgers,GB,QB,16,4299,48,5,149,3,1,-6,0,24.0,383.26
2,3,20889,Kyler Murray,ARI,QB,16,3971,26,12,819,11,0,0,0,23.7,378.74
3,4,18878,Alvin Kamara,NO,RB,15,0,0,0,932,16,83,756,5,25.2,377.80
4,5,18890,Patrick Mahomes,KC,QB,15,4740,38,6,308,2,0,0,0,25.0,374.40

In [68]:
ppr_2020.shape

(198, 16)